
blank_issues_enabled: true
contact_links:
  - name: ðŸš€ Feature Request
    url: https://github.com/simpleweb/open-format/discussions/categories/ideas
    about: Submit your own feature request, upvote an existing request or simply view our feature backlog
  - name: ðŸ¤” Support question
    url: https://github.com/simpleweb/open-format/discussions/new?category=question
    about: Issues are dedicated to bugs and documentation improvements, if you have questions, please use Github Discussions.
